Modules/Hrm/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('hrm')->group(function () {
    Route::get('/', [\Modules\Hrm\Http\Controllers\HrmController::class, 'index'])->name('hrm');
    Route::prefix('employee')->group(function () {
        Route::get('/departments/all', [\Modules\Hrm\Http\Controllers\DepartmentController::class, 'all'])->name('department.all');
        Route::get('/positions/all', [\Modules\Hrm\Http\Controllers\PositionController::class, 'all'])->name('position.all');
        Route::get(' / divisions / all', [\Modules\Hrm\Http\Controllers\DivisionController::class, 'all'])->name('division.all');
        Route::get('/employees/all', [\Modules\Hrm\Http\Controllers\EmployeeController::class, 'all'])->name('employee.all');
        Route::apiResources([
            'departments' => \Modules\Hrm\Http\Controllers\DepartmentController::class,
            'positions' => \Modules\Hrm\Http\Controllers\PositionController::class,
            'divisions' => \Modules\Hrm\Http\Controllers\DivisionController::class,
            'employees' => \Modules\Hrm\Http\Controllers\EmployeeController::class,
            'reschedules' => \Modules\Hrm\Http\Controllers\RescheduleController::class
        ]);
        Route::name('employees.')->group(function () {
            Route::apiResource('documents', \Modules\Hrm\Http\Controllers\EmployeeDocController::class);
        });
    });
    Route::get('/job-type/all', [\Modules\Hrm\Http\Controllers\JobTypeController::class, 'all'])->name('job_type.all');
    Route::get('/shift-schedules/all', [\Modules\Hrm\Http\Controllers\ShiftScheduleController::class, 'all'])->name('shift_schedule.all');
    Route::apiResources([
        'allowances' => \Modules\Hrm\Http\Controllers\AllowanceController::class,
        'shift-schedules' => \Modules\Hrm\Http\Controllers\ShiftScheduleController::class,
        'attendances' => \Modules\Hrm\Http\Controllers\AttendanceController::class,
        'loans' => \Modules\Hrm\Http\Controllers\LoanController::class,
    ]);
    Route::prefix('loan')->group(function () {
        Route::get('employees /{employee}/installments /{date?}', [\Modules\Hrm\Http\Controllers\LoanInstallmentController::class, 'installment'])->name('loans.employee.installment');
        Route::apiResources([
            'installments' => \Modules\Hrm\Http\Controllers\LoanInstallmentController::class
        ]);
    });
    Route::prefix('salaries')->name('salaries.')->group(function () {
        Route::apiResource('/generate', \Modules\Hrm\Http\Controllers\SalaryGenerationController::class)->only(['index','store']);
        Route::get('/salary/{salary}/change-status',[\Modules\Hrm\Http\Controllers\SalaryController::class, 'changeStatus'])->name('salary.change-status');
        Route::apiResource('/salary', \Modules\Hrm\Http\Controllers\SalaryController::class);
    });

    Route::prefix('leave')->name('leave.')->group(function () {
        Route::get('/types/all', [\Modules\Hrm\Http\Controllers\LeaveTypeController::class, 'all'])->name('types.all');
        Route::apiResources([
            'holidays' => \Modules\Hrm\Http\Controllers\HolidayController::class,
            'types' => \Modules\Hrm\Http\Controllers\LeaveTypeController::class,
            'applications' => \Modules\Hrm\Http\Controllers\LeaveApplicationController::class,
        ]);
    });
    Route::get('/grade/all', [\Modules\Hrm\Http\Controllers\GradeController::class, 'all'])->name('grade.all');
    Route::apiResource('grades', \Modules\Hrm\Http\Controllers\GradeController::class);

    Route::prefix('trainings')->name('trainings.')->group(function () {
        Route::get('/types/all', [\Modules\Hrm\Http\Controllers\TrainingTypeController::class, 'all'])->name('types.all');
        Route::get('/trainers/all', [\Modules\Hrm\Http\Controllers\TrainerController::class, 'all'])->name('trainers.all');
        Route::apiResources([
            'types' => \Modules\Hrm\Http\Controllers\TrainingTypeController::class,
            'trainers' => \Modules\Hrm\Http\Controllers\TrainerController::class,
            'workshops' => \Modules\Hrm\Http\Controllers\WorkshopController::class
        ]);
    });
    Route::prefix('report')->name('report.')->group(function () {
        Route::get('loan', [\Modules\Hrm\Http\Controllers\ReportController::class, 'loan'])->name('loan');
    });
    Route::name('hrm.')->group(function () {
        Route::apiResource('/settings', \Modules\Hrm\Http\Controllers\SettingsController::class)->only(['index','store']);
        Route::apiResource('/settings', \Modules\Hrm\Http\Controllers\SettingsController::class)->only(['index','store']);
    });

//    Common Menu items
    Route::get('/notices', [\Modules\Hrm\Http\Controllers\Common\NoticeController::class, 'index'])->name('hrm.notices.index');
    Route::get('/messenger', [\Modules\Hrm\Http\Controllers\Common\MessengerController::class, 'index'])->name('hrm.messenger.index');
    Route::get('/calender', [\Modules\Hrm\Http\Controllers\Common\CalenderController::class, 'index'])->name('hrm.calender.index');
    Route::get('/activities', [\Modules\Hrm\Http\Controllers\Common\ActivityController::class, 'index'])->name('hrm.activities.index');
    Route::get('/users', [\Modules\Hrm\Http\Controllers\Common\UserController::class, 'index'])->name('hrm.users.index');
    Route::get('/roles', [\Modules\Hrm\Http\Controllers\Common\RoleController::class, 'index'])->name('hrm.roles.index');
    Route::get('/user-role', [\Modules\Hrm\Http\Controllers\Common\UserRoleController::class, 'index'])->name('hrm.user-role.index');
    Route::get('/role-permission', [\Modules\Hrm\Http\Controllers\Common\RolePermissionController::class, 'index'])->name('hrm.role-permission.index');
    Route::get('/user-permission', [\Modules\Hrm\Http\Controllers\Common\UserPermissionController::class, 'index'])->name('hrm.user-permission.index');
    Route::get(' / languages', [\Modules\Hrm\Http\Controllers\Common\LanguageController::class, 'index'])->name('hrm.languages.index');
    Route::get('/languages/{language}/phrases',[\Modules\Hrm\Http\Controllers\Common\LanguagePhraseController::class, 'index'])->name('hrm.languages.phrases.index');
    Route::get('/phrases', [\Modules\Hrm\Http\Controllers\Common\PhraseController::class, 'index'])->name('hrm.phrases.index');
    Route::get('/currencies', [\Modules\Hrm\Http\Controllers\Common\CurrencyController::class, 'index'])->name('hrm.currencies.index');

    Route::post('/profile/change-password', [\Modules\Hrm\Http\Controllers\Common\ProfileController::class,'changePass'])->name('profile.update-password');
    Route::get('/profile', [\Modules\Hrm\Http\Controllers\Common\ProfileController::class, 'index'])->name('hrm.profile.index');
    Route::post('profile', [\Modules\Hrm\Http\Controllers\Common\ProfileController::class,'store']);
});

Modules/Hrm/Resources/views/department.blade.php
@extends('hrm::master')
@section('title')
    {{__('Departments')}}
@endsection
@section('content')
    {{--    Content Start--}}
    <div class="container-fluid">
        <div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-inbox bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{__('Departments')}}</h5>
                            <span>{{__('All Departments with their description')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('hrm')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0)">{{__('Employee')}}</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{__('Department')}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-block">
                        <h3 class="float-left"> {{__('Departments')}} </h3>
                        {{--                        Add Button--}}
                        @can('hrm-department-add')
                            <button type="button" class="btn btn-success float-right" data-toggle="modal"
                                    data-target="#departmentModal" data-whatever="0"> + {{__('Add Department')}}
                            </button>
                        @endcan
                    </div>
                    <div class="card-body">
                        <div class="dt-responsive">
                            {{--                            Department List start--}}
                            <table id="#" class="table nowrap">
                                <thead>
                                <tr>
                                    <th>{{__('ID')}}</th>
                                    <th>{{__('Department')}}</th>
                                    <th>{{__('Description')}}</th>
                                    <th>{{__('Created At')}}</th>
                                    <th class="text-right"></th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                            {{--                            Department List End--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Department Modal -->
    <div class="modal animated zoomIn faster" id="departmentModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">{{__('Department')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
{{--                Form Start--}}
                <form id="departmentForm" action="javascript:void(0)">
                    <div class="modal-body">
                        <div class="form-group row">
                            <label class="col-sm-4 col-lg-4 col-form-label">{{__('New Department')}}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" class="form-control" placeholder="{{__('name here')}}" name="name"
                                       required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-lg-4 col-form-label"
                                   for="exampleTextarea1">{{__('Description')}}</label>
                            <div class="col-sm-8 col-lg-8">
                                <textarea class="form-control" id="exampleTextarea1" rows="4"
                                          placeholder="{{__('description here')}}.." name="desc"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('Close')}}</button>
                        <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
                    </div>
                </form>
{{--                Form End--}}
            </div>
        </div>
    </div>
    {{--    Content End--}}
@endsection
@section('extraJS')
    <script>
        $(document).ready(function () {
            var oTable = $('.table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('departments.index') }}",
                deferRender: true,
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'desc', name: 'desc'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
            // Reset Form
            $('.modal').on('hidden.bs.modal', function (e) {
                $('form').trigger("reset");
            });
            // Show Modal
            $('.modal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget); // Button that triggered the modal
                var purpose = button.data('whatever'); // Extract info from data-* attributes

                var modal = $(this);
                if (purpose) {
                    modal.find('.modal-title').text('Edit Department');
                    var id = button.data('id');
                    $.ajax({
                        url: '{{route('departments.index')}}/' + id,
                        type: 'GET',
                        beforeSend: function (request) {
                            return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                        },
                        success: function (response) {
                            modal.find('input[name=name]').val(response.name);
                            modal.find('textarea[name=desc]').val(response.desc);
                        },
                        error: function (data) {
                            let msg = '';
                            if (data.responseJSON.errors) {
                                $.each(data.responseJSON.errors, function (i, error) {
                                    msg += '<p">' + error[0] + '</p>';
                                });
                            } else {
                                msg = data.responseJSON.message;
                            }
                            showDangerToast(msg);
                        }
                    });
                    modal.find('button[type=submit]').removeClass('save-btn').addClass('update-btn').text('{{__("Update")}}').val(id);
                } else {
                    modal.find('.modal-title').text('{{__("Add Department")}}');
                    modal.find('button[type=submit]').removeClass('update-btn').addClass('save-btn').text('{{__("Save")}}');
                }
            });
            // Save Event Listener
            $(document).on('click', '.save-btn', function () {
                let data = $('form').serialize();
                $.ajax({
                    url: '{{route('departments.store')}}',
                    type: 'POST',
                    data: data,
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        $('#departmentModal').modal('toggle');
                        $('form').trigger("reset");
                        showSuccessToast('{{__("Added Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
            // Update Event Listener
            $(document).on('click', '.update-btn', function () {
                let data = $('form').serialize();
                let id = $(this).val();
                $.ajax({
                    url: "{{ route('departments.index')}}/" + id,
                    type: 'PUT',
                    data: data,
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        $('#departmentModal').modal('toggle');
                        showSuccessToast('{{__("Updated Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
            // Delete Event Listener
            $(document).on('click', '.delete-btn', function (e) {
                e.preventDefault(); // does not go through with the link.
                var id = $(this).data('id');
                let confirmation = confirm("{{__('Are you sure to delete')}} ?");
                if (!confirmation) {
                    return;
                }
                $.ajax({
                    url: '{{ route('departments.index') }}/' + id,
                    type: 'DELETE',
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        showSuccessToast('{{__("Deleted Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
        });
    </script>
@endsection

Modules/Hrm/Resources/views/position.blade.php
@extends('hrm::master')
@section('title')
{{__('Position')}}
@endsection
@section('content')
{{--    Content start--}}
    <div class="container-fluid">
        <div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-inbox bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{__('Positions')}}</h5>
                            <span>{{__('All Positions with description are enlisted here')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('hrm')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0)">{{__('Employee')}}</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{__('Position')}}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-block">
                        <h3 class="float-left"> {{__('Positions')}} </h3>
{{--                        Add button--}}
                        @can('hrm-position-add')
                            <button type="button" class="btn btn-success float-right" data-toggle="modal"
                                    data-target="#positionModal" data-whatever="0"> + {{__('Add Position')}}
                            </button>
                        @endcan
                    </div>
                    <div class="card-body">
                        <div class="dt-responsive">
{{--                            Position list start--}}
                            <table id="#" class="table nowrap">
                                <thead>
                                <tr>
                                    <th>{{__('ID')}}</th>
                                    <th>{{__('Position')}}</th>
                                    <th>{{__('Description')}}</th>
                                    <th>{{__('Created At')}}</th>
                                    <th class="text-right"></th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
{{--                            Postion list end--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Position Modal -->
    <div class="modal animated zoomIn faster" id="positionModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">{{__('Position')}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="PositionForm" action="javascript:void(0)">
                    <div class="modal-body">
                        <div class="form-group row">
                            <label class="col-sm-4 col-lg-4 col-form-label">{{__('New Position')}}</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" class="form-control" placeholder="{{__('name here')}}" name="name" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-lg-4 col-form-label" for="exampleTextarea1">{{__('Description')}}</label>
                            <div class="col-sm-8 col-lg-8">
                                <textarea class="form-control" id="exampleTextarea1" rows="4"
                                          placeholder="{{__('description here')}}.." name="desc"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('Close')}}</button>
                        <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{{--    content end--}}
@endsection
@section('extraJS')
    <script>
        $(document).ready(function () {
            var oTable = $('.table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('positions.index') }}",
                deferRender: true,
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'desc', name: 'desc'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
            // Reset form
            $('.modal').on('hidden.bs.modal', function (e) {
                $('form').trigger("reset");
            });
            // Show modal
            $('.modal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget); // Button that triggered the modal
                var purpose = button.data('whatever'); // Extract info from data-* attributes

                var modal = $(this);
                if (purpose) {
                    modal.find('.modal-title').text('{{__("Edit Position")}}');
                    var id = button.data('id');
                    $.ajax({
                        url: '{{route('positions.index')}}/' + id,
                        type: 'GET',
                        beforeSend: function (request) {
                            return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                        },
                        success: function (response) {
                            modal.find('input[name=name]').val(response.name);
                            modal.find('textarea[name=desc]').val(response.desc);
                        },
                        error: function (data) {
                            let msg = '';
                            if (data.responseJSON.errors) {
                                $.each(data.responseJSON.errors, function (i, error) {
                                    msg += '<p">' + error[0] + '</p>';
                                });
                            } else {
                                msg = data.responseJSON.message;
                            }
                            showDangerToast(msg);
                        }
                    });
                    modal.find('button[type=submit]').removeClass('save-btn').addClass('update-btn').text('{{__("Update")}}').val(id);
                } else {
                    modal.find('.modal-title').text('{{__("Add Position")}}');
                    modal.find('button[type=submit]').removeClass('update-btn').addClass('save-btn').text('{{__("Save")}}');
                }
            });
            // Save event listener
            $(document).on('click', '.save-btn', function () {
                let data = $('form').serialize();
                $.ajax({
                    url: '{{route('positions.store')}}',
                    type: 'POST',
                    data: data,
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        $('#positionModal').modal('toggle');
                        $('form').trigger("reset");
                        showSuccessToast('{{__("Added Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
            // Update event listener
            $(document).on('click', '.update-btn', function () {
                let data = $('form').serialize();
                let id = $(this).val();
                $.ajax({
                    url: "{{ route('positions.index')}}/" + id,
                    type: 'PUT',
                    data: data,
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        $('#positionModal').modal('toggle');
                        showSuccessToast('{{__("Updated Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
            // delete event listener
            $(document).on('click', '.delete-btn', function (e) {
                e.preventDefault(); // does not go through with the link.
                let confirmation = confirm("{{__('Are you sure to delete')}} ?");
                if (!confirmation) {
                    return;
                }
                var id = $(this).data('id');
                $.ajax({
                    url: '{{ route('positions.index') }}/' + id,
                    type: 'DELETE',
                    beforeSend: function (request) {
                        return request.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content'));
                    },
                    success: function (response) {
                        showSuccessToast('{{__("Deleted Successfully")}}');
                        oTable.draw(false);
                    },
                    error: function (data) {
                        let msg = '';
                        if (data.responseJSON.errors) {
                            $.each(data.responseJSON.errors, function (i, error) {
                                msg += '<p">' + error[0] + '</p>';
                            });
                        } else {
                            msg = data.responseJSON.message;
                        }
                        showDangerToast(msg);
                    }
                });
            });
        });
    </script>
@endsection